backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/File"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Heading", name: "heading", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
